### ISSUE TITLE
[FIX] Correct Alignment of Icon and Text in Navigation Dropdown (Mobile View)

### ISSUE THREAD

**Issue by mayank-dev07** [Octasol/octasol#10]
**Description**

In the mobile view, the alignment of the icon and text in the navigation dropdown is inconsistent or incorrect. This affects the overall user experience and visual appeal, especially in responsive views. The alignment needs to be corrected to ensure a clean and professional look across all devices.

**Tasks**

Analyze the current alignment of the icon and text in the mobile view navigation dropdown.
Adjust the CSS or relevant styles to correct the alignment:
Ensure the icon and text are properly centered or aligned as per design guidelines.
Maintain consistency across different screen sizes and orientations.

**Test the alignment:**

Verify the changes in different screen sizes (mobile, tablet, etc.) to ensure responsiveness.
Test the dropdown for functionality and user interaction.

**Additional Information**

Ensure that the fix does not affect the alignment on desktop or larger screens.
Maintain the alignment consistency across all supported browsers.
Provide detailed commit messages that explain the changes made to correct the alignment.

**Expected Outcome**

The icon and text in the navigation dropdown should be properly aligned in the mobile view, leading to a better visual experience and usability on mobile devices.

**Comment by MichalT106** [comment]
Hi can you assign me? I would like to work on this issue.

**Comment by adilkadivala** [comment]
i want to work on this issue, please assign it me.

**Comment by mayank-dev07** [comment]
go ahead @adilkadivala

**Comment by A91y** [comment]
already fixed!
