### ISSUE TITLE
[Enhancement] Reduce the Loading Time of the Profile Page on Revisit

### ISSUE THREAD

**Issue by atj393** [Octasol/octasol#17]
Every time I visit the profile page, it takes a long time to load. While the loading time on the first visit is acceptable, subsequent visits result in a poor user experience due to the slow load time.

### **Suggested Enhancement**
To improve the user experience:
- **Show a draft version of the profile page** immediately, followed by a progress bar to indicate that the latest data is being fetched and updated.
- This will make the page feel more responsive, providing users with a better experience during revisits.

### **Impact**
- This enhancement will significantly improve the user experience, particularly for users who frequently revisit the profile page.
- It ensures that users can interact with the page while the latest data is being loaded, reducing frustration from waiting for content to refresh.

Let me know if this change aligns with the project’s goals!

**Comment by atj393** [comment]
@A91y If this topic is interesting, can you assign it to me?

**Comment by A91y** [comment]
Go Ahead @atj393
