### ISSUE TITLE
[Documentation] Create CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by LaraKraemer** [Octasol/octasol#6]
Issue: 
Missing Contributor Covenant Code of Conduct. 

Expected Outcome: 
Implementing a Contributor Covenant Code of Conduct can enhance your project’s appeal within the open-source community.

If you share my perspective on the importance of this document, I would be eager to take on this issue. Please let me know!

**Comment by A91y** [comment]
Feel free to contribute to this issue.
